// quiz_questions.js — Banco de perguntas do DAILY Quiz Arena
// 9 categorias, ~35 perguntas cada = ~315 perguntas

const QUESTION_BANK = [
  // ═══════════════════════ HISTÓRIA (35) ═══════════════════════
  { category:'historia', q:'Em que ano o Brasil declarou independência de Portugal?', opts:['1808','1822','1889','1840'], correct:1 },
  { category:'historia', q:'Quem proclamou a República do Brasil?', opts:['Dom Pedro II','Getúlio Vargas','Marechal Deodoro da Fonseca','Tiradentes'], correct:2 },
  { category:'historia', q:'Em que ano terminou a Segunda Guerra Mundial?', opts:['1943','1944','1945','1946'], correct:2 },
  { category:'historia', q:'Qual país lançou as primeiras bombas atômicas em combate?', opts:['URSS','Alemanha','Reino Unido','Estados Unidos'], correct:3 },
  { category:'historia', q:'Tiradentes foi executado em que século?', opts:['XVII','XVIII','XIX','XVI'], correct:1 },
  { category:'historia', q:'Quem foi o primeiro presidente do Brasil?', opts:['Floriano Peixoto','Deodoro da Fonseca','Campos Sales','Prudente de Morais'], correct:1 },
  { category:'historia', q:'A abolição da escravatura no Brasil ocorreu em:', opts:['1880','1884','1888','1890'], correct:2 },
  { category:'historia', q:'Qual foi o apelido dado à crise econômica iniciada em 1929?', opts:['Grande Recessão','Colapso de Wall Street','Grande Depressão','Crash do Ouro'], correct:2 },
  { category:'historia', q:'Quem assinou a Lei Áurea?', opts:['Dom Pedro I','Dom Pedro II','Princesa Isabel','Rui Barbosa'], correct:2 },
  { category:'historia', q:'Em que ano caiu o Muro de Berlim?', opts:['1987','1988','1989','1991'], correct:2 },
  { category:'historia', q:'Qual civilização construiu Machu Picchu?', opts:['Maia','Asteca','Inca','Olmeca'], correct:2 },
  { category:'historia', q:'Quem foi o líder da Revolução Francesa que depois se tornou imperador?', opts:['Luís XVI','Napoleão Bonaparte','Robespierre','Charles de Gaulle'], correct:1 },
  { category:'historia', q:'Em que ano começou a Primeira Guerra Mundial?', opts:['1912','1914','1916','1918'], correct:1 },
  { category:'historia', q:'Qual é o nome do navio que afundou em 1912 no Atlântico Norte?', opts:['Lusitania','Titanic','Britannic','Queen Mary'], correct:1 },
  { category:'historia', q:'Quem foi Zumbi dos Palmares?', opts:['Rei africano','Líder do Quilombo dos Palmares','General português','Bandeirante'], correct:1 },
  { category:'historia', q:'Em que ano o homem pisou na Lua pela primeira vez?', opts:['1965','1969','1971','1973'], correct:1 },
  { category:'historia', q:'Qual evento marcou o início da Era Vargas no Brasil?', opts:['Proclamação da República','Revolução de 1930','Golpe de 1964','Independência'], correct:1 },
  { category:'historia', q:'Quem foi Joana D’Arc?', opts:['Rainha da França','Heroína militar francesa','Imperatriz romana','Líder vikings'], correct:1 },
  { category:'historia', q:'A Guerra Fria foi um conflito entre quais potências?', opts:['EUA e China','EUA e URSS','Reino Unido e Alemanha','França e Rússia'], correct:1 },
  { category:'historia', q:'Em que ano o Brasil se tornou uma república?', opts:['1822','1889','1891','1900'], correct:1 },
  { category:'historia', q:'Qual foi o nome do primeiro imperador do Brasil?', opts:['Dom João VI','Dom Pedro I','Dom Pedro II','Dom Miguel'], correct:1 },
  { category:'historia', q:'Quem escreveu "O Príncipe", livro sobre política renascentista?', opts:['Dante Alighieri','Maquiavel','Thomas More','Erasmo de Roterdã'], correct:1 },
  { category:'historia', q:'A Grande Muralha da China foi construída principalmente para:', opts:['Comércio','Defesa contra invasões','Religião','Turismo'], correct:1 },
  { category:'historia', q:'Em que ano ocorreu o ataque a Pearl Harbor?', opts:['1939','1940','1941','1942'], correct:2 },
  { category:'historia', q:'Quem foi Getúlio Vargas?', opts:['Rei do Brasil','Presidente do Brasil por duas vezes','General da independência','Papa brasileiro'], correct:1 },
  { category:'historia', q:'O Império Romano caiu oficialmente em que século?', opts:['III','V','VII','IX'], correct:1 },
  { category:'historia', q:'Quem foi Cleópatra?', opts:['Rainha da Grécia','Última faraó do Egito','Imperatriz romana','Rainha da Pérsia'], correct:1 },
  { category:'historia', q:'A Revolução Industrial começou em qual país?', opts:['França','Alemanha','Inglaterra','Estados Unidos'], correct:2 },
  { category:'historia', q:'Quem foi Martin Luther King Jr.?', opts:['Presidente dos EUA','Líder dos direitos civis','Cientista','General'], correct:1 },
  { category:'historia', q:'Em que ano terminou a Ditadura Militar no Brasil?', opts:['1980','1983','1985','1988'], correct:2 },
  { category:'historia', q:'Quem foi o líder da independência da Índia através da não-violência?', opts:['Nehru','Mahatma Gandhi','Bose','Patel'], correct:1 },
  { category:'historia', q:'A Peste Negra atingiu a Europa principalmente em que século?', opts:['XII','XIV','XVI','XVIII'], correct:1 },
  { category:'historia', q:'Quem foi Alexandre, o Grande?', opts:['Rei persa','Conquistador macedônio','Imperador romano','Faraó egípcio'], correct:1 },
  { category:'historia', q:'O Brasil foi colônia de qual país europeu?', opts:['Espanha','Portugal','França','Holanda'], correct:1 },
  { category:'historia', q:'Em que ano foi assinada a Constituição dos Estados Unidos?', opts:['1776','1787','1800','1812'], correct:1 },

  // ═══════════════════════ GEOGRAFIA (35) ═══════════════════════
  { category:'geografia', q:'Qual é o maior país do mundo em área territorial?', opts:['China','Canadá','EUA','Rússia'], correct:3 },
  { category:'geografia', q:'Qual é o rio mais longo do mundo?', opts:['Amazonas','Nilo','Yangtzé','Mississippi'], correct:1 },
  { category:'geografia', q:'Qual é a capital da Austrália?', opts:['Sydney','Melbourne','Brisbane','Canberra'], correct:3 },
  { category:'geografia', q:'Em qual continente fica o Egito?', opts:['Ásia','Europa','África','Oceania'], correct:2 },
  { category:'geografia', q:'Quantos estados tem o Brasil?', opts:['24','25','26','27'], correct:3 },
  { category:'geografia', q:'Qual é o ponto mais alto do Brasil?', opts:['Pico da Neblina','Serra da Mantiqueira','Pico 31 de Março','Pedra da Mina'], correct:0 },
  { category:'geografia', q:'O Deserto do Saara fica em qual continente?', opts:['Ásia','África','América do Sul','Oceania'], correct:1 },
  { category:'geografia', q:'Qual país tem mais fronteiras terrestres?', opts:['Brasil','Rússia','China','Alemanha'], correct:2 },
  { category:'geografia', q:'Qual é a capital do Japão?', opts:['Osaka','Quioto','Tóquio','Yokohama'], correct:2 },
  { category:'geografia', q:'Qual é o menor país do mundo?', opts:['Mônaco','San Marino','Vaticano','Liechtenstein'], correct:2 },
  { category:'geografia', q:'O Monte Everest fica em qual cordilheira?', opts:['Andes','Alpes','Himalaia','Rochosas'], correct:2 },
  { category:'geografia', q:'Qual oceano é o maior do mundo?', opts:['Atlântico','Índico','Ártico','Pacífico'], correct:3 },
  { category:'geografia', q:'Qual é a capital da Itália?', opts:['Milão','Veneza','Roma','Florença'], correct:2 },
  { category:'geografia', q:'Em que continente fica o Peru?', opts:['América Central','América do Sul','América do Norte','Caribe'], correct:1 },
  { category:'geografia', q:'Qual é o maior deserto do mundo (considerando a Antártica)?', opts:['Saara','Gobi','Antártica','Arábico'], correct:2 },
  { category:'geografia', q:'Qual país tem o formato de bota na Europa?', opts:['Espanha','Itália','Grécia','Portugal'], correct:1 },
  { category:'geografia', q:'Qual é a capital da Argentina?', opts:['Córdoba','Rosário','Buenos Aires','Mendoza'], correct:2 },
  { category:'geografia', q:'O Canal do Panamá conecta quais oceanos?', opts:['Atlântico e Índico','Pacífico e Atlântico','Índico e Pacífico','Ártico e Pacífico'], correct:1 },
  { category:'geografia', q:'Qual é o maior lago de água doce do mundo em volume?', opts:['Lago Vitória','Mar Cáspio','Lago Baikal','Lago Superior'], correct:2 },
  { category:'geografia', q:'Quantos países fazem fronteira com o Brasil?', opts:['8','9','10','11'], correct:1 },
  { category:'geografia', q:'Qual é a capital da França?', opts:['Lyon','Marselha','Paris','Nice'], correct:2 },
  { category:'geografia', q:'A Cordilheira dos Andes percorre qual continente?', opts:['África','América do Sul','Ásia','Europa'], correct:1 },
  { category:'geografia', q:'Qual país é conhecido como "Terra do Sol Nascente"?', opts:['China','Coreia do Sul','Japão','Tailândia'], correct:2 },
  { category:'geografia', q:'Qual é o estado brasileiro com maior extensão territorial?', opts:['Pará','Minas Gerais','Bahia','Amazonas'], correct:3 },
  { category:'geografia', q:'Em qual continente está localizada a Groenlândia (politicamente)?', opts:['América do Norte','Europa','Ásia','Oceania'], correct:1 },
  { category:'geografia', q:'Qual é a capital do Canadá?', opts:['Toronto','Vancouver','Montreal','Ottawa'], correct:3 },
  { category:'geografia', q:'O Rio Nilo deságua em qual mar?', opts:['Mar Vermelho','Mar Mediterrâneo','Mar Negro','Mar Cáspio'], correct:1 },
  { category:'geografia', q:'Qual é o país mais populoso da África?', opts:['Egito','África do Sul','Nigéria','Etiópia'], correct:2 },
  { category:'geografia', q:'Qual cidade brasileira é conhecida como "Terra da Garoa"?', opts:['Rio de Janeiro','São Paulo','Curitiba','Porto Alegre'], correct:1 },
  { category:'geografia', q:'Qual é o maior arquipélago do mundo?', opts:['Filipinas','Japão','Indonésia','Maldivas'], correct:2 },
  { category:'geografia', q:'Em qual continente fica o Cazaquistão?', opts:['Europa','Ásia','Oriente Médio','Está em ambos Europa e Ásia'], correct:3 },
  { category:'geografia', q:'Qual é a linha imaginária que divide a Terra em hemisfério norte e sul?', opts:['Meridiano de Greenwich','Linha do Equador','Trópico de Câncer','Círculo Polar'], correct:1 },
  { category:'geografia', q:'Qual país tem o maior número de ilhas no mundo?', opts:['Filipinas','Suécia','Noruega','Finlândia'], correct:2 },
  { category:'geografia', q:'Qual é a capital de Portugal?', opts:['Porto','Lisboa','Faro','Coimbra'], correct:1 },
  { category:'geografia', q:'O Triângulo das Bermudas fica em qual oceano?', opts:['Pacífico','Índico','Atlântico','Ártico'], correct:2 },

  // ═══════════════════════ CIÊNCIAS (35) ═══════════════════════
  { category:'ciencias', q:'Qual é o elemento químico mais abundante no universo?', opts:['Oxigênio','Hélio','Carbono','Hidrogênio'], correct:3 },
  { category:'ciencias', q:'Quantos ossos tem o corpo humano adulto?', opts:['196','206','216','226'], correct:1 },
  { category:'ciencias', q:'Qual é o planeta mais próximo do Sol?', opts:['Vênus','Terra','Mercúrio','Marte'], correct:2 },
  { category:'ciencias', q:'A fórmula da água é:', opts:['H3O','OH2','HO','H2O'], correct:3 },
  { category:'ciencias', q:'DNA significa:', opts:['Ácido Desoxirribonucleico','Ácido Dinitroamínico','Dupla Nucleotídica Ativa','Ácido Dinucleico'], correct:0 },
  { category:'ciencias', q:'Quantos cromossomos tem o ser humano?', opts:['23','44','46','48'], correct:2 },
  { category:'ciencias', q:'Qual é o órgão responsável por bombear sangue pelo corpo?', opts:['Pulmão','Fígado','Coração','Rim'], correct:2 },
  { category:'ciencias', q:'Quem propôs a Teoria da Evolução das Espécies?', opts:['Isaac Newton','Charles Darwin','Albert Einstein','Gregor Mendel'], correct:1 },
  { category:'ciencias', q:'Qual é a velocidade da luz aproximadamente?', opts:['150 mil km/s','300 mil km/s','450 mil km/s','600 mil km/s'], correct:1 },
  { category:'ciencias', q:'Qual gás as plantas absorvem na fotossíntese?', opts:['Oxigênio','Nitrogênio','Gás carbônico','Hidrogênio'], correct:2 },
  { category:'ciencias', q:'Quem desenvolveu a Teoria da Relatividade?', opts:['Isaac Newton','Albert Einstein','Stephen Hawking','Niels Bohr'], correct:1 },
  { category:'ciencias', q:'Qual é o maior órgão do corpo humano?', opts:['Fígado','Cérebro','Pele','Pulmão'], correct:2 },
  { category:'ciencias', q:'Quantos planetas existem no Sistema Solar atualmente?', opts:['7','8','9','10'], correct:1 },
  { category:'ciencias', q:'Qual é a unidade básica da vida?', opts:['Átomo','Molécula','Célula','Tecido'], correct:2 },
  { category:'ciencias', q:'O que estuda a Geologia?', opts:['Seres vivos','Estrutura da Terra','Clima','Estrelas'], correct:1 },
  { category:'ciencias', q:'Qual vitamina é produzida pelo corpo com a luz solar?', opts:['Vitamina A','Vitamina C','Vitamina D','Vitamina K'], correct:2 },
  { category:'ciencias', q:'Qual é o metal líquido em temperatura ambiente?', opts:['Ferro','Mercúrio','Chumbo','Alumínio'], correct:1 },
  { category:'ciencias', q:'Quantos litros de sangue tem em média um adulto?', opts:['3 litros','5 litros','7 litros','9 litros'], correct:1 },
  { category:'ciencias', q:'Qual é o animal terrestre mais rápido do mundo?', opts:['Leão','Guepardo','Gazela','Cavalo'], correct:1 },
  { category:'ciencias', q:'O que é a fotossíntese?', opts:['Respiração das plantas','Processo de produção de energia das plantas via luz','Reprodução vegetal','Crescimento de raízes'], correct:1 },
  { category:'ciencias', q:'Qual é o osso mais longo do corpo humano?', opts:['Úmero','Fêmur','Tíbia','Rádio'], correct:1 },
  { category:'ciencias', q:'Quantos sentidos básicos o ser humano possui?', opts:['4','5','6','7'], correct:1 },
  { category:'ciencias', q:'Qual cientista formulou as leis do movimento e da gravidade?', opts:['Galileu Galilei','Isaac Newton','Albert Einstein','Johannes Kepler'], correct:1 },
  { category:'ciencias', q:'O que é um vulcão?', opts:['Montanha de gelo','Abertura na crosta terrestre que expele magma','Tipo de rocha','Fenômeno climático'], correct:1 },
  { category:'ciencias', q:'Qual é a camada da atmosfera mais próxima da Terra?', opts:['Estratosfera','Troposfera','Mesosfera','Termosfera'], correct:1 },
  { category:'ciencias', q:'O Sol é uma:', opts:['Planeta','Estrela','Lua','Cometa'], correct:1 },
  { category:'ciencias', q:'Qual gás é essencial para a respiração humana?', opts:['Nitrogênio','Gás carbônico','Oxigênio','Hidrogênio'], correct:2 },
  { category:'ciencias', q:'Quantos pares de cromossomos o ser humano possui?', opts:['21','22','23','24'], correct:2 },
  { category:'ciencias', q:'Qual animal é conhecido por mudar de cor para se camuflar?', opts:['Iguana','Camaleão','Salamandra','Lagarto'], correct:1 },
  { category:'ciencias', q:'O que é o efeito estufa?', opts:['Resfriamento da Terra','Retenção de calor na atmosfera','Movimento das placas tectônicas','Ciclo da água'], correct:1 },
  { category:'ciencias', q:'Qual é a maior célula do corpo humano?', opts:['Neurônio','Óvulo','Hemácia','Espermatozoide'], correct:1 },
  { category:'ciencias', q:'Quem descobriu a penicilina?', opts:['Louis Pasteur','Alexander Fleming','Robert Koch','Marie Curie'], correct:1 },
  { category:'ciencias', q:'Qual é o processo de transformação de líquido em gás?', opts:['Condensação','Solidificação','Evaporação','Sublimação'], correct:2 },
  { category:'ciencias', q:'Quantos ossos tem a coluna vertebral humana?', opts:['26','30','33','36'], correct:2 },
  { category:'ciencias', q:'Marie Curie ganhou o Prêmio Nobel em quais áreas?', opts:['Física e Química','Física e Medicina','Química e Medicina','Apenas Física'], correct:0 },

  // ═══════════════════════ CULTURA POP (35) ═══════════════════════
  { category:'cultura_pop', q:'Qual é a franquia de filmes mais lucrativa de todos os tempos?', opts:['Harry Potter','Star Wars','Marvel Cinematic Universe','James Bond'], correct:2 },
  { category:'cultura_pop', q:'Quem criou o personagem Mickey Mouse?', opts:['Walt Disney','Roy Disney','Ub Iwerks','Chuck Jones'], correct:2 },
  { category:'cultura_pop', q:'Qual banda britânica vendeu mais discos na história?', opts:['Rolling Stones','Led Zeppelin','The Beatles','Queen'], correct:2 },
  { category:'cultura_pop', q:'O jogo Minecraft foi criado por:', opts:['Notch (Markus Persson)','Gabe Newell','Todd Howard','Shigeru Miyamoto'], correct:0 },
  { category:'cultura_pop', q:'Quantas temporadas tem a série Breaking Bad?', opts:['3','4','5','6'], correct:2 },
  { category:'cultura_pop', q:'Qual artista é conhecido como "Rei do Pop"?', opts:['Prince','Michael Jackson','Elvis Presley','Stevie Wonder'], correct:1 },
  { category:'cultura_pop', q:'Em qual app foi popularizado o formato de vídeos curtos verticais?', opts:['Instagram','TikTok','YouTube','Snapchat'], correct:1 },
  { category:'cultura_pop', q:'Qual é o nome do bruxo da série de livros de J.K. Rowling?', opts:['Frodo','Harry Potter','Percy Jackson','Eragon'], correct:1 },
  { category:'cultura_pop', q:'Qual cantora é conhecida por hits como "Shake It Off" e "Anti-Hero"?', opts:['Ariana Grande','Taylor Swift','Billie Eilish','Dua Lipa'], correct:1 },
  { category:'cultura_pop', q:'Qual é o jogo eletrônico mais vendido de todos os tempos?', opts:['GTA V','Minecraft','Tetris','Fortnite'], correct:1 },
  { category:'cultura_pop', q:'Qual rede social foi fundada por Mark Zuckerberg?', opts:['Twitter','Instagram','Facebook','LinkedIn'], correct:2 },
  { category:'cultura_pop', q:'Qual artista brasileiro é conhecido como "Rei do Brega"?', opts:['Reginaldo Rossi','Roberto Carlos','Wando','Amado Batista'], correct:0 },
  { category:'cultura_pop', q:'Qual é o nome do protagonista da saga "John Wick"?', opts:['John Smith','John Wick','James Bond','Jason Bourne'], correct:1 },
  { category:'cultura_pop', q:'Quem interpretou a personagem Hermione Granger nos filmes de Harry Potter?', opts:['Emma Watson','Emma Stone','Emma Roberts','Emily Blunt'], correct:0 },
  { category:'cultura_pop', q:'Qual é o nome do streaming de música do Spotify concorrente?', opts:['Apple Music','iTunes','Pandora','Deezer'], correct:0 },
  { category:'cultura_pop', q:'Qual super-herói é conhecido como "O Homem de Ferro"?', opts:['Steve Rogers','Tony Stark','Bruce Banner','Peter Parker'], correct:1 },
  { category:'cultura_pop', q:'Qual cantora brasileira é conhecida por "Ai Se Eu Te Pego"?', opts:['Anitta','Ivete Sangalo','Claudia Leitte','Michel Teló'], correct:3 },
  { category:'cultura_pop', q:'Qual é o nome do criador da Marvel Comics?', opts:['Bob Kane','Stan Lee','Jack Kirby','Frank Miller'], correct:1 },
  { category:'cultura_pop', q:'Qual jogo de cartas colecionáveis envolve "duelistas" e cartas mágicas?', opts:['Magic: The Gathering','Pokémon TCG','Yu-Gi-Oh!','Hearthstone'], correct:2 },
  { category:'cultura_pop', q:'Quem é o protagonista da série "Stranger Things"?', opts:['Mike Wheeler','Eleven','Dustin Henderson','Will Byers'], correct:1 },
  { category:'cultura_pop', q:'Qual é o reality show mais antigo do Brasil ainda no ar?', opts:['A Fazenda','Big Brother Brasil','MasterChef Brasil','The Voice Brasil'], correct:1 },
  { category:'cultura_pop', q:'Qual é o nome do robô protagonista de "WALL-E"?', opts:['EVE','WALL-E','R2-D2','Baymax'], correct:1 },
  { category:'cultura_pop', q:'Qual rapper brasileiro lançou o álbum "Sobre Viver"?', opts:['Emicida','Criolo','Racionais MCs','BK'], correct:0 },
  { category:'cultura_pop', q:'Qual é o nome do vilão principal de "O Rei Leão"?', opts:['Mufasa','Simba','Scar','Zazu'], correct:2 },
  { category:'cultura_pop', q:'Qual cantor pop é conhecido por "Blinding Lights"?', opts:['Drake','The Weeknd','Justin Bieber','Ed Sheeran'], correct:1 },
  { category:'cultura_pop', q:'Em qual cidade fictícia se passa o filme "Batman"?', opts:['Metrópolis','Gotham City','Star City','Central City'], correct:1 },
  { category:'cultura_pop', q:'Qual é o nome do app de chamadas de vídeo popularizado durante a pandemia?', opts:['Skype','Zoom','Discord','Teams'], correct:1 },
  { category:'cultura_pop', q:'Qual série retrata a ascensão de um professor de química ao crime organizado?', opts:['Narcos','Breaking Bad','Ozark','The Wire'], correct:1 },
  { category:'cultura_pop', q:'Quem canta o hit "Envolver"?', opts:['Karol G','Anitta','Becky G','Shakira'], correct:1 },
  { category:'cultura_pop', q:'Qual é o nome do dragão de estimação de Hagrid em Harry Potter?', opts:['Norberto','Fawkes','Aragog','Buckbeak'], correct:0 },
  { category:'cultura_pop', q:'Qual jogo é conhecido por construções no estilo "battle royale" com 100 jogadores?', opts:['Apex Legends','Fortnite','Valorant','Overwatch'], correct:1 },
  { category:'cultura_pop', q:'Quem é o autor da saga de livros "O Senhor dos Anéis"?', opts:['George R.R. Martin','J.R.R. Tolkien','C.S. Lewis','Terry Pratchett'], correct:1 },
  { category:'cultura_pop', q:'Qual é o nome da banda de K-pop mais famosa globalmente?', opts:['BLACKPINK','EXO','BTS','TWICE'], correct:2 },
  { category:'cultura_pop', q:'Qual personagem da Disney perdeu o sapatinho de cristal?', opts:['Branca de Neve','Cinderela','Bela','Ariel'], correct:1 },
  { category:'cultura_pop', q:'Qual cantor brasileiro é conhecido como "Rei do Funk"?', opts:['MC Kevinho','MC Guimê','Mr. Catra','Bonde do Tigrão'], correct:2 },

  // ═══════════════════════ ESPORTES (35) ═══════════════════════
  { category:'esportes', q:'Quantas Copas do Mundo o Brasil conquistou?', opts:['4','5','6','3'], correct:1 },
  { category:'esportes', q:'Em que país foi realizada a Copa do Mundo de 2018?', opts:['Alemanha','Rússia','Brasil','Catar'], correct:1 },
  { category:'esportes', q:'Qual esporte é praticado no Wimbledon?', opts:['Golfe','Cricket','Tênis','Polo'], correct:2 },
  { category:'esportes', q:'Qual time ganhou mais títulos da NBA?', opts:['LA Lakers','Chicago Bulls','Boston Celtics','Golden State Warriors'], correct:2 },
  { category:'esportes', q:'A maratona tem quantos km?', opts:['40','41','42,195','43'], correct:2 },
  { category:'esportes', q:'Quantos jogadores tem um time de vôlei em quadra?', opts:['5','6','7','8'], correct:1 },
  { category:'esportes', q:'Qual país sediou as Olimpíadas de 2016?', opts:['China','Reino Unido','Brasil','Japão'], correct:2 },
  { category:'esportes', q:'Quantos sets são necessários para vencer uma partida de vôlei (melhor de 5)?', opts:['2','3','4','5'], correct:1 },
  { category:'esportes', q:'Qual é o nome do troféu da Champions League?', opts:['Taça Jules Rimet','Orelhuda','Copa Libertadores','Taça da UEFA'], correct:1 },
  { category:'esportes', q:'Quem é considerado o "Rei do Futebol"?', opts:['Maradona','Pelé','Ronaldinho','Zico'], correct:1 },
  { category:'esportes', q:'Qual país tem mais medalhas olímpicas de ouro na história?', opts:['China','Rússia','Estados Unidos','Alemanha'], correct:2 },
  { category:'esportes', q:'Em qual esporte se usa o termo "ace"?', opts:['Vôlei','Tênis','Basquete','Golfe'], correct:1 },
  { category:'esportes', q:'Quantos jogadores tem um time de basquete em quadra?', opts:['4','5','6','7'], correct:1 },
  { category:'esportes', q:'Qual nadador brasileiro é multimedalhista olímpico em natação?', opts:['Thiago Pereira','César Cielo','Bruno Fratus','Gabriel Santos'], correct:1 },
  { category:'esportes', q:'Em que esporte Michael Jordan se destacou?', opts:['Futebol americano','Beisebol','Basquete','Tênis'], correct:2 },
  { category:'esportes', q:'Qual é a distância de uma prova de 100 metros rasos?', opts:['100 jardas','100 metros','110 metros','90 metros'], correct:1 },
  { category:'esportes', q:'Quantos jogadores compõem um time de handebol em quadra?', opts:['5','6','7','8'], correct:2 },
  { category:'esportes', q:'Qual país é tricampeão consecutivo de Copa do Mundo (60,62,70 - quase)?', opts:['Alemanha','Itália','Brasil','Argentina'], correct:2 },
  { category:'esportes', q:'Quem é o piloto com mais títulos de Fórmula 1?', opts:['Ayrton Senna','Michael Schumacher','Lewis Hamilton','Sebastian Vettel'], correct:1 },
  { category:'esportes', q:'Qual é o nome do estádio do Real Madrid?', opts:['Camp Nou','Santiago Bernabéu','San Siro','Wembley'], correct:1 },
  { category:'esportes', q:'Em qual modalidade compete Usain Bolt?', opts:['Natação','Atletismo','Ciclismo','Salto'], correct:1 },
  { category:'esportes', q:'Quantos pontos vale um touchdown no futebol americano?', opts:['3','5','6','7'], correct:2 },
  { category:'esportes', q:'Qual seleção venceu a primeira Copa do Mundo, em 1930?', opts:['Brasil','Argentina','Uruguai','Itália'], correct:2 },
  { category:'esportes', q:'Qual é o esporte olímpico que usa um disco chamado "puck"?', opts:['Basquete no gelo','Hóquei no gelo','Curling','Patinação'], correct:1 },
  { category:'esportes', q:'Quantas vezes o Flamengo já foi campeão da Libertadores?', opts:['1','2','3','4'], correct:2 },
  { category:'esportes', q:'Qual é o nome do golpe de nocaute no boxe?', opts:['Jab','KO','Cross','Hook'], correct:1 },
  { category:'esportes', q:'Em que esporte se usa o termo "birdie"?', opts:['Tênis','Golfe','Badminton','Squash'], correct:1 },
  { category:'esportes', q:'Qual jogador venceu mais Bolas de Ouro?', opts:['Cristiano Ronaldo','Lionel Messi','Pelé','Zidane'], correct:1 },
  { category:'esportes', q:'Quantos jogadores compõem uma equipe de rúgbi em campo?', opts:['11','13','15','17'], correct:2 },
  { category:'esportes', q:'Qual é o nome da competição de clubes mais importante da América do Sul?', opts:['Copa Sul-Americana','Copa Libertadores','Recopa','Copa América'], correct:1 },
  { category:'esportes', q:'Quem detém o recorde de gols em uma única edição de Copa do Mundo?', opts:['Pelé','Ronaldo','Just Fontaine','Klose'], correct:2 },
  { category:'esportes', q:'Qual é o nome do movimento de defesa no vôlei feito com os braços para cima?', opts:['Ataque','Bloqueio','Saque','Levantamento'], correct:1 },
  { category:'esportes', q:'Em qual cidade nasceu o futebol moderno?', opts:['Paris','Londres','Madrid','Roma'], correct:1 },
  { category:'esportes', q:'Quantos minutos dura uma partida oficial de futebol (sem prorrogação)?', opts:['80','90','100','120'], correct:1 },
  { category:'esportes', q:'Qual brasileiro venceu o US Open de tênis?', opts:['Gustavo Kuerten','Thomaz Bellucci','Thiago Wild','João Fonseca'], correct:0 },

  // ═══════════════════════ CINEMA (35) ═══════════════════════
  { category:'cinema', q:'Qual filme ganhou mais Oscars na história?', opts:['Titanic','Ben-Hur','O Senhor dos Anéis: O Retorno do Rei','Gandhi'], correct:2 },
  { category:'cinema', q:'Quem dirigiu o filme "Pulp Fiction"?', opts:['Martin Scorsese','Steven Spielberg','Quentin Tarantino','Francis Ford Coppola'], correct:2 },
  { category:'cinema', q:'Qual ator interpretou o Coringa no filme de 2019?', opts:['Jared Leto','Heath Ledger','Joaquin Phoenix','Jack Nicholson'], correct:2 },
  { category:'cinema', q:'O filme "Parasita" que ganhou o Oscar de Melhor Filme é de qual país?', opts:['Japão','China','Coreia do Sul','Tailândia'], correct:2 },
  { category:'cinema', q:'Quem dirigiu a trilogia original "Star Wars"?', opts:['Steven Spielberg','George Lucas','James Cameron','Ridley Scott'], correct:1 },
  { category:'cinema', q:'Qual filme tem a frase "Eu vou voltar"?', opts:['Rambo','O Exterminador do Futuro','Duro de Matar','RoboCop'], correct:1 },
  { category:'cinema', q:'Quem interpretou Jack em "Titanic"?', opts:['Brad Pitt','Leonardo DiCaprio','Matt Damon','Tom Cruise'], correct:1 },
  { category:'cinema', q:'Qual é o filme de maior bilheteria da história?', opts:['Vingadores: Ultimato','Titanic','Avatar','Star Wars'], correct:2 },
  { category:'cinema', q:'Quem dirigiu "O Poderoso Chefão"?', opts:['Martin Scorsese','Francis Ford Coppola','Stanley Kubrick','Sidney Lumet'], correct:1 },
  { category:'cinema', q:'Qual estúdio é responsável por "Toy Story"?', opts:['DreamWorks','Pixar','Illumination','Warner Bros'], correct:1 },
  { category:'cinema', q:'Quem interpreta Tony Stark/Homem de Ferro no MCU?', opts:['Chris Evans','Chris Hemsworth','Robert Downey Jr.','Mark Ruffalo'], correct:2 },
  { category:'cinema', q:'Qual filme brasileiro ganhou o Oscar de Melhor Filme Internacional em 2025?', opts:['Cidade de Deus','Ainda Estou Aqui','Bacurau','Aquarius'], correct:1 },
  { category:'cinema', q:'Quem dirigiu "Interestelar"?', opts:['Denis Villeneuve','Christopher Nolan','Ridley Scott','James Cameron'], correct:1 },
  { category:'cinema', q:'Qual ator interpretou Forrest Gump?', opts:['Tom Hanks','Tom Cruise','Kevin Costner','Robin Williams'], correct:0 },
  { category:'cinema', q:'Em qual filme aparece a frase "Que a força esteja com você"?', opts:['Star Trek','Star Wars','Jornada nas Estrelas','Duna'], correct:1 },
  { category:'cinema', q:'Qual filme de terror apresenta o personagem Michael Myers?', opts:['Sexta-Feira 13','Halloween','Pesadelo em Elm Street','Pânico'], correct:1 },
  { category:'cinema', q:'Quem dirigiu "Tubarão" (1975)?', opts:['George Lucas','Steven Spielberg','Ridley Scott','James Cameron'], correct:1 },
  { category:'cinema', q:'Qual atriz interpretou a Mulher-Maravilha nos filmes recentes?', opts:['Scarlett Johansson','Gal Gadot','Brie Larson','Margot Robbie'], correct:1 },
  { category:'cinema', q:'Qual filme retrata a história de Oppenheimer e a bomba atômica?', opts:['Dunkirk','Oppenheimer','A Lista de Schindler','1917'], correct:1 },
  { category:'cinema', q:'Quem interpretou o personagem Wolverine na franquia X-Men?', opts:['Ryan Reynolds','Hugh Jackman','Patrick Stewart','Ian McKellen'], correct:1 },
  { category:'cinema', q:'Qual filme animado retrata a vida de um peixe-palhaço em busca do filho?', opts:['Procurando Nemo','Vida Marinha','Shark Tale','Procurando Dory'], correct:0 },
  { category:'cinema', q:'Quem dirigiu "Matrix" (1999)?', opts:['Irmãos Coen','Irmãs Wachowski','Christopher Nolan','David Fincher'], correct:1 },
  { category:'cinema', q:'Qual ator interpreta Batman no filme "Batman" de 2022?', opts:['Christian Bale','Ben Affleck','Robert Pattinson','George Clooney'], correct:2 },
  { category:'cinema', q:'Qual filme brasileiro de 2002 retrata a violência no Rio de Janeiro?', opts:['Tropa de Elite','Cidade de Deus','Central do Brasil','Carandiru'], correct:1 },
  { category:'cinema', q:'Quem interpretou Hermione Granger em Harry Potter?', opts:['Emma Watson','Bonnie Wright','Evanna Lynch','Katie Leung'], correct:0 },
  { category:'cinema', q:'Qual estúdio criou os filmes "Como Treinar o Seu Dragão"?', opts:['Pixar','DreamWorks','Illumination','Blue Sky'], correct:1 },
  { category:'cinema', q:'Quem dirigiu "Coringa" (2019)?', opts:['Christopher Nolan','Todd Phillips','Zack Snyder','Matt Reeves'], correct:1 },
  { category:'cinema', q:'Qual ator interpretou Neo em Matrix?', opts:['Brad Pitt','Will Smith','Keanu Reeves','Tom Cruise'], correct:2 },
  { category:'cinema', q:'Qual filme conta a história de Elsa e Anna em um reino congelado?', opts:['Moana','Frozen','Enrolados','Vaiana'], correct:1 },
  { category:'cinema', q:'Quem interpreta Mia Wallace em "Pulp Fiction"?', opts:['Uma Thurman','Sharon Stone','Demi Moore','Susan Sarandon'], correct:0 },
  { category:'cinema', q:'Qual filme retrata a vida do físico Stephen Hawking?', opts:['Uma Mente Brilhante','A Teoria de Tudo','O Jogo da Imitação','Genius'], correct:1 },
  { category:'cinema', q:'Qual diretor é conhecido por filmes como "Bastardos Inglórios" e "Kill Bill"?', opts:['Robert Rodriguez','Quentin Tarantino','David Fincher','Wes Anderson'], correct:1 },
  { category:'cinema', q:'Quem interpretou o personagem Tony Montana em "Scarface"?', opts:['Robert De Niro','Al Pacino','Joe Pesci','James Caan'], correct:1 },
  { category:'cinema', q:'Qual é o filme de animação mais lucrativo da história?', opts:['Frozen II','Divertida Mente 2','Procurando Dory','Toy Story 4'], correct:1 },
  { category:'cinema', q:'Quem dirigiu a saga "O Senhor dos Anéis"?', opts:['Guillermo del Toro','Peter Jackson','James Cameron','Ridley Scott'], correct:1 },

  // ═══════════════════════ TECNOLOGIA (35) ═══════════════════════
  { category:'tecnologia', q:'Quem cofundou a Apple com Steve Jobs?', opts:['Bill Gates','Steve Wozniak','Elon Musk','Paul Allen'], correct:1 },
  { category:'tecnologia', q:'O que significa "HTTP"?', opts:['Hyper Text Transfer Protocol','High Tech Transfer Platform','Hyper Typed Transfer Page','Hub Text Tool Protocol'], correct:0 },
  { category:'tecnologia', q:'Qual linguagem de programação é mais usada no mundo?', opts:['Java','C++','Python','JavaScript'], correct:3 },
  { category:'tecnologia', q:'Em que ano o Instagram foi lançado?', opts:['2009','2010','2011','2012'], correct:1 },
  { category:'tecnologia', q:'O criador do Linux se chama:', opts:['Linus Torvalds','Richard Stallman','Dennis Ritchie','Ken Thompson'], correct:0 },
  { category:'tecnologia', q:'Qual empresa criou o sistema operacional Windows?', opts:['Apple','Microsoft','Google','IBM'], correct:1 },
  { category:'tecnologia', q:'O que significa "AI" em tecnologia?', opts:['Automated Internet','Artificial Intelligence','Advanced Integration','Applied Informatics'], correct:1 },
  { category:'tecnologia', q:'Qual foi a primeira rede social popular antes do Facebook?', opts:['MySpace','Orkut','Friendster','LinkedIn'], correct:0 },
  { category:'tecnologia', q:'Quem fundou a Tesla e a SpaceX?', opts:['Jeff Bezos','Elon Musk','Mark Zuckerberg','Larry Page'], correct:1 },
  { category:'tecnologia', q:'O que é um "bug" em programação?', opts:['Vírus de computador','Erro no código','Tipo de hardware','Linguagem de programação'], correct:1 },
  { category:'tecnologia', q:'Qual empresa é dona do YouTube?', opts:['Meta','Amazon','Google','Microsoft'], correct:2 },
  { category:'tecnologia', q:'O que significa "URL"?', opts:['Universal Resource Locator','Uniform Resource Locator','United Resource Link','Universal Reference Link'], correct:1 },
  { category:'tecnologia', q:'Qual é o navegador mais usado no mundo?', opts:['Firefox','Safari','Edge','Chrome'], correct:3 },
  { category:'tecnologia', q:'Quem criou o Facebook?', opts:['Bill Gates','Mark Zuckerberg','Larry Page','Steve Jobs'], correct:1 },
  { category:'tecnologia', q:'O que é "cloud computing"?', opts:['Processamento local','Armazenamento e processamento via internet','Tipo de hardware','Sistema de impressão'], correct:1 },
  { category:'tecnologia', q:'Qual empresa criou o ChatGPT?', opts:['Google','Microsoft','OpenAI','Meta'], correct:2 },
  { category:'tecnologia', q:'O que significa "RAM" em um computador?', opts:['Random Access Memory','Read Access Memory','Rapid Access Module','Remote Access Memory'], correct:0 },
  { category:'tecnologia', q:'Quem é o atual CEO da Microsoft (desde 2014)?', opts:['Bill Gates','Steve Ballmer','Satya Nadella','Sundar Pichai'], correct:2 },
  { category:'tecnologia', q:'Qual rede social é focada em vídeos curtos e foi criada na China?', opts:['Instagram','TikTok','Snapchat','Vine'], correct:1 },
  { category:'tecnologia', q:'O que é um "firewall"?', opts:['Tipo de vírus','Sistema de segurança de rede','Linguagem de programação','Tipo de hardware'], correct:1 },
  { category:'tecnologia', q:'Qual empresa fabrica o iPhone?', opts:['Samsung','Apple','Google','Sony'], correct:1 },
  { category:'tecnologia', q:'O que significa "Wi-Fi"?', opts:['Wireless Fidelity','Wide Fiber','Wireless File','Web Interface'], correct:0 },
  { category:'tecnologia', q:'Qual foi o primeiro smartphone da Apple?', opts:['iPhone 3G','iPhone original (2007)','iPhone 4','iPhone 3GS'], correct:1 },
  { category:'tecnologia', q:'Quem fundou a Amazon?', opts:['Elon Musk','Jeff Bezos','Bill Gates','Larry Ellison'], correct:1 },
  { category:'tecnologia', q:'O que é "open source"?', opts:['Software pago','Software com código aberto','Tipo de hardware','Sistema fechado'], correct:1 },
  { category:'tecnologia', q:'Qual linguagem é usada para estruturar páginas web?', opts:['CSS','JavaScript','HTML','Python'], correct:2 },
  { category:'tecnologia', q:'Qual é o nome do assistente virtual da Amazon?', opts:['Siri','Alexa','Cortana','Google Assistant'], correct:1 },
  { category:'tecnologia', q:'O que significa "USB"?', opts:['Universal Serial Bus','United System Board','Universal System Bus','United Serial Board'], correct:0 },
  { category:'tecnologia', q:'Qual empresa desenvolveu o Android?', opts:['Apple','Google','Samsung','Microsoft'], correct:1 },
  { category:'tecnologia', q:'O que é criptomoeda?', opts:['Moeda física rara','Moeda digital descentralizada','Tipo de cartão de crédito','Sistema bancário'], correct:1 },
  { category:'tecnologia', q:'Qual foi a primeira criptomoeda criada?', opts:['Ethereum','Bitcoin','Litecoin','Dogecoin'], correct:1 },
  { category:'tecnologia', q:'O que significa "VPN"?', opts:['Virtual Private Network','Virtual Public Network','Verified Private Network','Variable Private Network'], correct:0 },
  { category:'tecnologia', q:'Qual empresa é conhecida pelo processador chamado "M1" e "M2"?', opts:['Intel','AMD','Apple','Qualcomm'], correct:2 },
  { category:'tecnologia', q:'O que é um "algoritmo"?', opts:['Tipo de hardware','Sequência de instruções para resolver um problema','Linguagem de programação','Vírus de computador'], correct:1 },
  { category:'tecnologia', q:'Qual rede social foi a antecessora do Twitter/X em formato de microblogging?', opts:['Tumblr','Orkut','Não houve antecessora direta','MySpace'], correct:2 },

  // ═══════════════════════ CONHECIMENTOS GERAIS (35) ═══════════════════════
  { category:'geral', q:'Qual é o livro mais vendido da história?', opts:['O Senhor dos Anéis','Quijote','A Bíblia','Harry Potter'], correct:2 },
  { category:'geral', q:'Qual é o país mais populoso do mundo?', opts:['Índia','China','EUA','Indonésia'], correct:0 },
  { category:'geral', q:'Em que continente fica o Monte Everest?', opts:['África','Europa','Ásia','América'], correct:2 },
  { category:'geral', q:'Qual é o instrumento musical de cordas mais antigo?', opts:['Guitarra','Harpa','Violino','Lira'], correct:1 },
  { category:'geral', q:'Quantos países fazem parte da ONU?', opts:['173','193','203','213'], correct:1 },
  { category:'geral', q:'Qual é a moeda oficial do Japão?', opts:['Won','Yuan','Iene','Rupia'], correct:2 },
  { category:'geral', q:'Quantos dias tem um ano bissexto?', opts:['364','365','366','367'], correct:2 },
  { category:'geral', q:'Qual é a língua mais falada do mundo (nativos)?', opts:['Inglês','Espanhol','Mandarim','Hindi'], correct:2 },
  { category:'geral', q:'Quem pintou a Mona Lisa?', opts:['Michelangelo','Leonardo da Vinci','Rafael','Donatello'], correct:1 },
  { category:'geral', q:'Qual é o animal terrestre mais pesado do mundo?', opts:['Rinoceronte','Hipopótamo','Elefante','Girafa'], correct:2 },
  { category:'geral', q:'Quantas cordas tem um violão clássico?', opts:['4','5','6','7'], correct:2 },
  { category:'geral', q:'Qual é a capital cultural conhecida por seus museus em Paris?', opts:['Louvre','Orsay','Pompidou','Todos são museus em Paris'], correct:3 },
  { category:'geral', q:'Quem escreveu "Dom Quixote"?', opts:['Gabriel García Márquez','Miguel de Cervantes','Jorge Luis Borges','Pablo Neruda'], correct:1 },
  { category:'geral', q:'Qual é o maior mamífero do mundo?', opts:['Elefante','Baleia-azul','Tubarão-baleia','Girafa'], correct:1 },
  { category:'geral', q:'Quantas cores tem o arco-íris?', opts:['5','6','7','8'], correct:2 },
  { category:'geral', q:'Qual é o prato típico mais famoso da Itália?', opts:['Paella','Pizza','Sushi','Curry'], correct:1 },
  { category:'geral', q:'Quem escreveu "Romeu e Julieta"?', opts:['Charles Dickens','William Shakespeare','Jane Austen','Oscar Wilde'], correct:1 },
  { category:'geral', q:'Qual é a montanha mais alta do mundo?', opts:['K2','Monte Everest','Kilimanjaro','Aconcágua'], correct:1 },
  { category:'geral', q:'Quantas teclas tem um piano padrão?', opts:['76','88','92','100'], correct:1 },
  { category:'geral', q:'Qual é o animal símbolo da China?', opts:['Tigre','Panda gigante','Dragão','Tartaruga'], correct:1 },
  { category:'geral', q:'Quem pintou "A Noite Estrelada"?', opts:['Pablo Picasso','Vincent van Gogh','Claude Monet','Salvador Dalí'], correct:1 },
  { category:'geral', q:'Qual é a fruta mais consumida no mundo?', opts:['Maçã','Banana','Tomate','Laranja'], correct:2 },
  { category:'geral', q:'Quantos minutos tem um dia?', opts:['1200','1440','1600','1800'], correct:1 },
  { category:'geral', q:'Qual é o nome do escritor brasileiro autor de "Dom Casmurro"?', opts:['José de Alencar','Machado de Assis','Graciliano Ramos','Jorge Amado'], correct:1 },
  { category:'geral', q:'Qual é a bebida mais consumida no mundo depois da água?', opts:['Café','Chá','Refrigerante','Suco'], correct:1 },
  { category:'geral', q:'Quantos lados tem um hexágono?', opts:['5','6','7','8'], correct:1 },
  { category:'geral', q:'Qual é o oceano que banha o litoral leste do Brasil?', opts:['Pacífico','Atlântico','Índico','Ártico'], correct:1 },
  { category:'geral', q:'Quem compôs a "Nona Sinfonia"?', opts:['Mozart','Bach','Beethoven','Chopin'], correct:2 },
  { category:'geral', q:'Qual é o metal mais precioso (referência clássica)?', opts:['Prata','Platina','Ouro','Bronze'], correct:2 },
  { category:'geral', q:'Quantos continentes existem no mundo (modelo mais comum)?', opts:['5','6','7','8'], correct:2 },
  { category:'geral', q:'Qual escritor criou o detetive Sherlock Holmes?', opts:['Agatha Christie','Arthur Conan Doyle','Edgar Allan Poe','Charles Dickens'], correct:1 },
  { category:'geral', q:'Qual é o animal nacional da Austrália?', opts:['Coala','Canguru','Dingo','Vombate'], correct:1 },
  { category:'geral', q:'Quantos quilômetros tem aproximadamente a circunferência da Terra?', opts:['30 mil km','40 mil km','50 mil km','60 mil km'], correct:1 },
  { category:'geral', q:'Qual é a especiaria mais cara do mundo?', opts:['Canela','Cravo','Açafrão','Baunilha'], correct:2 },
  { category:'geral', q:'Quem escreveu "Memórias Póstumas de Brás Cubas"?', opts:['José de Alencar','Machado de Assis','Lima Barreto','Euclides da Cunha'], correct:1 },

  // ═══════════════════════ FUTEBOL (35) ═══════════════════════
  { category:'futebol', q:'Quantos jogadores tem um time de futebol em campo?', opts:['10','11','12','9'], correct:1 },
  { category:'futebol', q:'Qual clube tem mais títulos da Copa Libertadores?', opts:['Flamengo','Boca Juniors','Estudiantes','Independiente'], correct:3 },
  { category:'futebol', q:'Quem marcou a "Mão de Deus" na Copa de 1986?', opts:['Pelé','Ronaldo','Maradona','Zico'], correct:2 },
  { category:'futebol', q:'Em que ano o Brasil ganhou sua primeira Copa do Mundo?', opts:['1950','1954','1958','1962'], correct:2 },
  { category:'futebol', q:'Qual estádio tem maior capacidade no Brasil?', opts:['Maracanã','Mineirão','Morumbi','Castelão'], correct:0 },
  { category:'futebol', q:'Qual clube brasileiro é conhecido como "Mengão"?', opts:['Fluminense','Flamengo','Vasco','Botafogo'], correct:1 },
  { category:'futebol', q:'Quem é o maior artilheiro da história das Copas do Mundo?', opts:['Pelé','Ronaldo Fenômeno','Miroslav Klose','Just Fontaine'], correct:2 },
  { category:'futebol', q:'Qual seleção é conhecida como "La Albiceleste"?', opts:['Uruguai','Argentina','Chile','Colômbia'], correct:1 },
  { category:'futebol', q:'Em que cidade fica o estádio Camp Nou?', opts:['Madrid','Barcelona','Sevilha','Valência'], correct:1 },
  { category:'futebol', q:'Qual jogador é apelidado de "El Pibe de Oro"?', opts:['Messi','Maradona','Riquelme','Tevez'], correct:1 },
  { category:'futebol', q:'Quantos gols Pelé marcou oficialmente em sua carreira (aprox.)?', opts:['Mais de 500','Mais de 700','Mais de 1000','Mais de 1200'], correct:2 },
  { category:'futebol', q:'Qual time é o maior rival do Corinthians em São Paulo?', opts:['São Paulo FC','Palmeiras','Santos','Todos são rivais'], correct:3 },
  { category:'futebol', q:'Em que país nasceu Cristiano Ronaldo?', opts:['Espanha','Brasil','Portugal','Itália'], correct:2 },
  { category:'futebol', q:'Qual é o nome do estádio do Flamengo (mandante)?', opts:['Maracanã','Engenhão','Vila Belmiro','São Januário'], correct:0 },
  { category:'futebol', q:'Quantas Copas do Mundo a Alemanha já venceu?', opts:['2','3','4','5'], correct:2 },
  { category:'futebol', q:'Qual jogador brasileiro ficou conhecido como "Fenômeno"?', opts:['Romário','Ronaldo Nazário','Ronaldinho Gaúcho','Rivaldo'], correct:1 },
  { category:'futebol', q:'Em que ano o Brasil sediou a Copa do Mundo pela última vez antes de 2014?', opts:['1950','1970','1994','2002'], correct:0 },
  { category:'futebol', q:'Qual seleção venceu a Copa do Mundo de 2022?', opts:['França','Brasil','Argentina','Croácia'], correct:2 },
  { category:'futebol', q:'Qual clube paulista é conhecido como "Verdão"?', opts:['São Paulo','Corinthians','Palmeiras','Santos'], correct:2 },
  { category:'futebol', q:'Quem é o técnico mais vitorioso da história da Champions League?', opts:['Pep Guardiola','Carlo Ancelotti','Zinedine Zidane','Alex Ferguson'], correct:1 },
  { category:'futebol', q:'Qual é o apelido do clube Vasco da Gama?', opts:['Gigante da Colina','Cruz-Maltino','Imortal Tricolor','Glorioso'], correct:1 },
  { category:'futebol', q:'Quantos toques um goleiro pode dar na bola com as mãos dentro da área antes de soltar?', opts:['Sem limite','6 segundos','10 segundos','15 segundos'], correct:1 },
  { category:'futebol', q:'Qual jogador venceu mais Bolas de Ouro da história?', opts:['Cristiano Ronaldo','Messi','Pelé','Maradona'], correct:1 },
  { category:'futebol', q:'Em que país fica o clube Manchester United?', opts:['Escócia','País de Gales','Inglaterra','Irlanda'], correct:2 },
  { category:'futebol', q:'Qual seleção é conhecida como "Canarinho"?', opts:['Colômbia','Brasil','Equador','Uruguai'], correct:1 },
  { category:'futebol', q:'Quantos jogadores reservas podem ser inscritos em uma súmula de jogo (padrão recente)?', opts:['7','9','12','15'], correct:2 },
  { category:'futebol', q:'Qual é o nome do estádio do Real Madrid?', opts:['Camp Nou','Santiago Bernabéu','Wanda Metropolitano','San Mamés'], correct:1 },
  { category:'futebol', q:'Qual clube brasileiro tem o maior número de títulos do Campeonato Brasileiro?', opts:['Flamengo','Corinthians','Palmeiras','Santos'], correct:2 },
  { category:'futebol', q:'Quem foi o capitão do Brasil na Copa de 2002?', opts:['Ronaldo','Cafu','Roberto Carlos','Rivaldo'], correct:1 },
  { category:'futebol', q:'Qual é a duração de uma prorrogação no futebol?', opts:['15 minutos','20 minutos','30 minutos','45 minutos'], correct:2 },
  { category:'futebol', q:'Em qual país fica o clube Bayern de Munique?', opts:['Áustria','Suíça','Alemanha','Holanda'], correct:2 },
  { category:'futebol', q:'Qual seleção sul-americana nunca foi campeã mundial?', opts:['Chile','Colômbia','Equador','Todas as anteriores'], correct:3 },
  { category:'futebol', q:'Quem marcou o gol do título do Brasil na Copa de 1994?', opts:['Romário','Bebeto','A decisão foi por pênaltis, sem gol na prorrogação','Ronaldo'], correct:2 },
  { category:'futebol', q:'Qual é o nome do prêmio dado ao melhor jogador da Copa do Mundo?', opts:['Bola de Ouro da Copa','Chuteira de Ouro','Bola de Prata','Bola de Bronze'], correct:0 },
  { category:'futebol', q:'Qual time inglês é conhecido como "Reds"?', opts:['Manchester United','Liverpool','Arsenal','Chelsea'], correct:1 },
];

module.exports = { QUESTION_BANK };
